### ISSUE TITLE
Item name height changes won't apply on first join

### ISSUE THREAD

**Issue by derNiklaas** [Noxcrew/noxesium#10]
## Short description 
The height of item names aren't being applied when first joining island, only after switching the lobby or joining the game. 

## How to reproduce
Join Island and switch to another item in your hotbar (first item). After that, change to another lobby and select an item in your hotbar (second item). 

## Expected behavior
Both item texts float above the faction icon.

## Observed behaviour
The first item text clips into the faction icon, while the second item text floats above the faction icon.

## Minecraft Version and Mods
Minecraft 1.19.4, fabric api 0.76.0, forcecloseloadingscreen 1.2.0, iris 1.5.2, lithium 1.11.1, sodium 0.4.10+build.24, spark 1.10.34, starlight 1.1.1, Noxesium 0.1.8

## Images 
On first join: 
![image](https://user-images.githubusercontent.com/12937331/226037421-10dc910a-27d4-4ae4-a951-b2067008b37d.png)

After switching the lobby: 
![image](https://user-images.githubusercontent.com/12937331/226037663-9bdb0f43-92e4-4bc4-8f81-2b28cd2e0faa.png)

**Comment by Aeltumn** [comment]
Fixed in v1.0.0.
