### ISSUE TITLE
Qibs are not registered client-side until an interactionWidthZ is set

### ISSUE THREAD

**Issue by SuperNeon4ik** [Noxcrew/noxesium#105]
The client seems to not register a Qib until an `interactionWidthZ` of not 1.0 is provided.

My uneducated guess is that this is the only place where the interaction entity is added to the `SpatialInteractionEntityTree` and when sending a setExtraData packet with only `qibBehavior` doesn't register the Qib. Sending a packet with `interactionWidthZ` (or sending it along with the `qibBehavior`) helps, unless the width is `1.0`. Which is probably the result of the `!aABB.equals(getBoundingBox())` check.
https://github.com/Noxcrew/noxesium/blob/e9708058e24d67b9f9014457145920b29c6ec63d/fabric/src/main/java/com/noxcrew/noxesium/mixin/rules/qib/SpatialEntityMixin.java#L25-L27

I'm not too good with Minecraft mods to actually know what is happening and how to fix it, but just wanted to share my thoughts.

### How to reproduce
1. Send setExtraData packet with a `qibBehavior`
2. Client won't recognize the Qib, until `interactionWidthZ` is set to a non-1 value

### Video of the issue
[2024-09-30 20-46-36.webm](https://github.com/user-attachments/assets/51fe8c02-21ef-4bd4-b63b-379f152ba5d1)

### System information
Server version: 1.21.1 (Paper)
Noxesium/Paper version: https://github.com/Noxcrew/noxesium/commit/e9708058e24d67b9f9014457145920b29c6ec63d (unpublished build)
Client version: 1.21
Noxesium/fabric version: 2.3.2+88430aa

**Comment by Aeltumn** [comment]
There is a bug here, but it's not specifically the z-width being set. The interaction entity is only added to the tree if it's position is updated at any point, which can also be from being moved. The bug here is that it's not properly added on spawn if it never moves. A temporary workaround is to set an interaction width or teleport it after spawning.

**Comment by Aeltumn** [comment]
Do you have any details about what the interaction entity you are spawning looks like? Because I can confirm that interaction entities are being added to the spatial container even if they have no qib behavior or interaction width at all.

**Comment by SuperNeon4ik** [comment]
I am spawning it just with `/summon minecraft:interaction`

Actually interesting thing I've noticed is I am getting rebuilds:
- `[22:44:21] [Noxesium Spatial Container Rebuild Thread/INFO]: [CHAT] §eRebuilt spatial model, before: §f[0, 2, 0]§e, after: §f[0, 0, 0]` on join (i had 2 interaction entities without any extra data)
- `[22:46:01] [Noxesium Spatial Container Rebuild Thread/INFO]: [CHAT] §eRebuilt spatial model, before: §f[0, 1, 0]§e, after: §f[0, 0, 0]` when summoned
- when I give it a qibBehavior it doesn't rebuild.
- 0` [22:49:21] [Noxesium Spatial Container Rebuild Thread/INFO]: [CHAT] §eRebuilt spatial model, before: §f[0, 1, 0]§e, after: §f[1, 0, 0]` when i update the interaction width (entities in model only here becomes 1)

[Трансляція_20240930_225223.webm](https://github.com/user-attachments/assets/2b48588d-3429-4ca9-9242-58b44c8296b0)

**Comment by Aeltumn** [comment]
So I guess what is happening here is somehow the spatial container rebuilds in between the entity creation and it being added to the world.

**Comment by SuperNeon4ik** [comment]
That is kind of what happens. 
![image](https://github.com/user-attachments/assets/c15305a7-0b41-41db-b44f-84fdf8c18a60)

It does get discarded BUT. Currently (i never restarted the server) I have two interactions with entityIds of 44 and 46, but the client tries to add absolutely random ids and I can't figure out why and how.

After a reboot my ID's rn are 51 & 52, but client tries to add 147 & 148:
*(added `text.add(Component.literal("§bCrosshair entity: §7" + Minecraft.getInstance().crosshairPickEntity)); ` to `TextHudOverlayWrapper`)*
![image](https://github.com/user-attachments/assets/eefe04ee-dc57-4677-b8c9-7c83dc14a955)
And in the debugger they've got the right IDs too:
![image](https://github.com/user-attachments/assets/d51d3509-757b-4b87-bfb5-f69dbc405d91)
![image](https://github.com/user-attachments/assets/82d2ffef-0be1-4c66-b7a6-62f66ed71d02)

Adding an output in the `SpatialInteractionEntityTree.update` gives this (entity ids still are 51 & 52:
![image](https://github.com/user-attachments/assets/4ba4985c-9164-4541-9a24-1b36ea2b093f)

Removing the bounding box check in `SpatialEntityMixin` reveals that it actually gets the ID right the 3rd time, but probably on this third time the bounding box doesn't get updates, so it doesn't attempt to update:
![image](https://github.com/user-attachments/assets/234b3c60-506f-42a1-9f63-1d73faee04d3)

Removing the bounding box check is obviously not a solution, because it just spams rebuilds rn.

Sorry, that it took so long to reply. Hopefully this is not too hard to read, because I was writing it while investigating the issue, so I didn't know the exact problem at the start. Hope this helps!

**Comment by Aeltumn** [comment]
Interesting, the ids are different because the client auto-assigns new ids before the server's id overrides it.

**Comment by SuperNeon4ik** [comment]
Yeah, I guess that is exactly what happens. Just tried it and it also happens in a singleplayer world, so it's not a paper thing

**Comment by SuperNeon4ik** [comment]
Yup, that fixes it! All interactables are now added properly when loaded
