### ISSUE TITLE
Offhand Durability Bug

### ISSUE THREAD

**Issue by real-greg** [Noxcrew/noxesium#111]
On 1.21.3, If a tool or weapon breaks when you have a shield in your offhand, the shield disappears.  

Steps to reproduce

Put a shield in the offhand, and fully use up a tool's durability.

Video

https://github.com/user-attachments/assets/cbeca866-e8e3-4453-a7c5-e74838de6177

**Comment by real-greg** [comment]
The only mods installed are Fabric API and Noxesium.

**Comment by Aeltumn** [comment]
I cannot recreate this issue with those same mods. I don't know how Noxesium would break something like this in the first place as it does not modify item slots.

**Comment by Aeltumn** [comment]
Turns out it does not occur when breaking a block but does occur when attacking an entity with the last durability.

**Comment by Aeltumn** [comment]
Found the issue, it is something quite oddly specific and causes a client desync. Thank you for finding something so obscure!
