### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by om3ga6400** [Noxcrew/noxesium#119]
So I was reporting a start up crash to the create mod and they said you have a bad mixing here's the log: https://mclo.gs/wycA4F7

**Comment by Aeltumn** [comment]
This issue has been fixed in later updates of Noxesium, please update Noxesium or remove the mod from your modpack.

**Comment by om3ga6400** [comment]
I think I'm on the newest vet for 1.20.1

**Comment by om3ga6400** [comment]
I think I'm on the newest vet for 1.20.1

**Comment by Aeltumn** [comment]
I don't support older versions, Noxesium does not have any version on 1.20.1 with this issue fixed. You'll have to not use Noxesium or update.
