### ISSUE TITLE
Self-compiled build not detected on MCCI

### ISSUE THREAD

**Issue by LifeDreamer24** [Noxcrew/noxesium#15]
Compiled the latest commit that supports 1.20.1 apparently but the setting to see player heads is still showing up as strikethrough on the server.

Are the public/available versions whitelisted serverside?

Thanks in advance,
-Simon

**Comment by Aeltumn** [comment]
The 1.20 version is currently unfinished as I'm quite busy and haven't had time to finish it. The version updating itself is finished but I'm restructing the API for future changes. The most recent version that will work with MCCi is the 1.19.4 version on Modrinth.
