### ISSUE TITLE
Suggestion / Bug Report: Fix Cloaks with Iris / Optifine Shaders, as well as general Modded + Vanilla shader compatability if possible

### ISSUE THREAD

**Issue by Kaizodude** [Noxcrew/noxesium#18]
As the title suggests, Cloaks break when enabling shaders with Iris or Optifine. 
![image](https://github.com/Noxcrew/noxesium/assets/2174905/052f54ca-19b4-451c-9e9e-6a859d2a4fca)
![image](https://github.com/Noxcrew/noxesium/assets/2174905/614a15b9-b9c2-4a70-91de-ee423e5a72c9)
![image](https://github.com/Noxcrew/noxesium/assets/2174905/2272a3e5-7a01-4c8e-8d59-919064cadadf)
Other things such as emissive lighting from entities breaks, I'm aware this may be trickier however

**Comment by Aeltumn** [comment]
Fixing bugs in other mods is not within the scope of Noxesium.
