### ISSUE TITLE
Crashes When Using Sodium

### ISSUE THREAD

**Issue by ignSotrix** [Noxcrew/noxesium#23]
All I use is Sodium and Noxesium (tested with v1 and v1.0.1). This is all that it shows.

Error: java.lang.NoClassDefFoundError:
me/jellysquid/mods/sodium/client/model/color/interop/ItemColorsExtended

**Comment by Aeltumn** [comment]
You need to use at least Sodium 0.5 with the latest version of Noxesium. Sodium made breaking changes so we can't support the older version.
