### ISSUE TITLE
"Stuttering" Caused By Noxesium

### ISSUE THREAD

**Issue by LobbyLC** [Noxcrew/noxesium#24]
A friend of mine has been experiencing "stuttering" (common, barely noticable FPS drops lasting less than a second) while playing Battle Box on MCC Island and we've managed to narrow it down to being an issue with Noxesium. We don't know exactly why it's happening, but we do know it's not the case when Noxesium isn't installed. I've attached a little more information and a short clip demonstrating the stuttering below!

This report isn't really "helpful", but I thought I'd share what we know so you could potentially look into it! (It's worth noting that I also use Noxesium and have never once had this issue, which is why I'm a little confused by it haha)

Mods Used:
- [Fabric API](https://modrinth.com/mod/fabric-api/version/0.87.0+1.20.1)
- [Noxesium](https://modrinth.com/mod/noxesium/version/1.0.2)
- [Sodium](https://modrinth.com/mod/sodium/version/mc1.20.1-0.5.1)

Device Specifications:
- Intel i7-8750H
- 16GB RAM (4GB Allocated)
- NVIDIA GeForce GTX 1670

https://github.com/Noxcrew/noxesium/assets/116382138/a43d0bf6-c595-494d-af6e-4294304d37c0

**Comment by Aeltumn** [comment]
Can you confirm that these stutters do not happen when only using Sodium?
Regardess of that, could you install this mod https://modrinth.com/mod/spark and run it using `/sparkc profiler start`? It basically generates a report on what code is being run on your client and what is causing lag spikes.

**Comment by LobbyLC** [comment]
When only using Sodium, my friend didn't experience any stutterring so we reinstalled Noxesium and ran the profiler. Here's the link to the results of that after a full Battle Box game: https://spark.lucko.me/GOyoK3iL7u

**Comment by Aeltumn** [comment]
Unfortunately I don't think I can do anything about this without a lot more information and testing which would be a lot harder to organise. I have had no other reports of anything like this happening for anyone else and stuttering like this in general is quite odd. The spark report did not indicate any particular lag sources, and you need to do some specific settings regardless to properly catch what could be causing stuttering specifically. The only suggestion I could give is to update video card drivers or to ensure that Minecraft is using the correct video card. (e.g. no intergrated graphics)

As for the part where this only happens with Noxesium.. I really don't understand how that can happen. Noxesium does nothing that should be able to cause something like this. None of Noxesium's changes go deep enough into the rendering code that I could see it cause such core issues, it's just really weird.
