### ISSUE TITLE
Dependency import failing

### ISSUE THREAD

**Issue by TheFox580** [Noxcrew/noxesium#25]
When I try to import any version of Noxesium to my plugin, I get the constant warning : 

`[WARNING] The POM for com.noxcrew.noxesium:api:jar:1.0.2 is missing, no dependency information available`

followed by a build failure for the reason :

`The following artifacts could not be resolved: com.noxcrew.noxesium:api:jar:1.0.2 (absent): com.noxcrew.noxesium:api:jar:1.0.2 was not found in https://maven.noxcrew.com/ during a previous attempt.` 

I keep trying to clean and install my build (with `mvn clean install`) but I get the same result everywhere

(Same error with Noxesium 1.0.0 and 1.0.1)

![image](https://github.com/Noxcrew/noxesium/assets/44817153/09959f8f-af01-4a73-8a36-844a05c1216e)

(Probably me being dumb and not being able to import Noxesium despite having the repository and dependency setup correctly)

![image](https://github.com/Noxcrew/noxesium/assets/44817153/c14802f6-6d01-4f3e-b8de-ca6e087d51fd)
![image](https://github.com/Noxcrew/noxesium/assets/44817153/fd2aa1a4-202e-420a-b47a-89010647294d)

**Comment by clrxbl** [comment]
The README.md contains an invalid repository URL, could you please try https://maven.noxcrew.com/public ?
