### ISSUE TITLE
Weird rendering of display entities

### ISSUE THREAD

**Issue by LiamDun** [Noxcrew/noxesium#26]
Using v1.0.3
I've noticed that after the recent update to how display entities work their culling is also different (referring to the display entity on the right coming from the barber shop), I checked and this doesn't happen in vanilla.
https://github.com/Noxcrew/noxesium/assets/62409548/30111d6b-3e32-4900-808e-6106781dbf19

**Comment by Aeltumn** [comment]
The background still being visible through the wall is intended and matches how entity name tags render, the issue here is that the text isn't rendering through the wall.

**Comment by Aeltumn** [comment]
Merging into #28
