### ISSUE TITLE
Heads blipping up in the HUD 

### ISSUE THREAD

**Issue by Kaizodude** [Noxcrew/noxesium#27]
![image](https://github.com/Noxcrew/noxesium/assets/2174905/4570cae8-3f12-4f96-a9ac-cabf94ca529e)
Occurred multiple times last night while playing Battle Box with friends, another friend who also had Noxesium installed (presumably from the MCC Island optimized pack on the forums) also experienced the same issue with the same player heads

**Comment by Kaizodude** [comment]
I believe a way to replicate this is to be in a party with users who have the MCC+ rank on MCC Island

**Comment by Aeltumn** [comment]
Will be fixed in the next server-side MCC island update.
