### ISSUE TITLE
Text Display backgrounds are visible through walls

### ISSUE THREAD

**Issue by 16CSmoke** [Noxcrew/noxesium#28]
When using the mod, text display backgrounds remain visible through walls, when they should not be visible. This still happens even with the NBT option of {see_through} is set to false.

This does not happen with any other mods.

![2023-09-18_13 55 08](https://github.com/Noxcrew/noxesium/assets/145394230/9acc16a1-aff4-481e-809e-7c1513bab775)

**Comment by Aeltumn** [comment]
This is an intentional change as it mimics how text backgrounds display for entity name tags. It is a bug however that the text is not visible through the wall.

**Comment by 16CSmoke** [comment]
Okay I understand, but is there any way we can prevent it from being the case on the server side at all? I have people comm

**Comment by 16CSmoke** [comment]
(Didn’t intent to mark this as closed, was a misclick)

**Comment by Aeltumn** [comment]
Hmm, I could move this behaviour to the see_through flag as that allows servers to opt-in since the flag is effectively useless in its current state anyway. It makes the text itself get rendered behind everything else.

**Comment by 16CSmoke** [comment]
Yeah, that would be great! Being able to control their visibility through walls would be a massive help. Thanks!

**Comment by LukynkaCZE** [comment]
Agree with @16CSmoke, we switched to text displays as custom nametags deliberately because they don't render through walls, ability to send packet to control this would be nice

**Comment by Aeltumn** [comment]
After more consideration I'm changing it to still fix that non-see through text displays render nothing behind them, but instead simply making text displays still not render through walls. Not rendering through walls is useful and reduces clutter, additionally having them render through walls would negatively impact performance.
