### ISSUE TITLE
Crash on startup due to a mixin issue

### ISSUE THREAD

**Issue by ChromaPIE** [Noxcrew/noxesium#35]
Crash report: https://pastebin.com/h6SVJxec

Kinda sure it's not only caused by Noxesium itself bc the game was fine booting up before one/more mods got updated/added.

**Comment by ChromaPIE** [comment]
still a crash when using 1.0.5, im on 1.20.1 btw and i actually edited fabric.mod.json to make the game start to boot up without a warning popup

**Comment by Aeltumn** [comment]
1.0.5 only works on 1.20.2. The crash you got there is from using the wrong version.

**Comment by Aeltumn** [comment]
This bug is also already fixed on 1.20.2.
