### ISSUE TITLE
Suggestion: fix desync issues with Noxesium

### ISSUE THREAD

**Issue by kispintyi** [Noxcrew/noxesium#40]
It would be cool if you could solve the crossbow falsely loaded in issue for high ping players (I have 125+-ms), It is so annoying when I want to shoot but the crossbow just starts to load in an arrow but for me, it was already loaded in (visual glitch)
this issue happens when I release the RMB so early that my client thinks I loaded the crossbow in but on the server this isn't the case because of my ping (the same issue happens when I try to run so fast that my FOV vibrates and the server and client can't decide it if I'm running or not) these are maybe solvable with Noxesium because as far as I'm aware Noxesium is connected to the server in some way and I think it can fix this issue by sending the server a fix info that I'm not running and didn't charge the crossbow fully and visually updating it on the client side or I don't know)
Video: https://cdn.discordapp.com/attachments/1134515300742733985/1181239391977476116/Clip_-_2023_12_04_151925.mp4?ex=658055e9&is=656de0e9&hm=67c7df56eb80265c2290d8499fc1572531148b897992defb5dca27cfb81b234d&

The food and the (drinkable) bottles are okay and if I don't wait for my character (my client) to finish the food/drink fully it drinks/eats it so yeah that is ahead but the crossbow isn't, the crossbow works the other way around.

oh and I have an issue where the people charge their bow (not crossbow) and for me, it doesn't show that they charged their bow it just looks like they are staring at me and I get hit by an arrow coming from them and there is another ping issue too which makes charging weapons (like swords, axes, etc.) even more time to charge because if I pull my sword or any weapon I need to charge it but after 0.5 seconds it charges it again (like resets it and starts charging it again) making the time charging it even slower and it gives me a disadvantage (this only happens if I switch to that weapon)

and here is the sprint issue (where it cannot detect if I'm running or walking properly because of the ping and it just vibrates my view and sometimes sprints, sometimes walks)
Video: https://cdn.discordapp.com/attachments/1134515300742733985/1181580656812228678/Clip_-_2023_12_05_135228.mp4?ex=658193bd&is=656f1ebd&hm=1c207c242ea0fc85222a08074103b72839f98cb659dc38de696834c0e9276da0&
ignore the lagback I had high ping becuase I was uploading files xd but it was easier this way to reproduce the issue that happens at around 125ms ping, only there it just vibrates as long as I don't stop and can't decide what I'm doing, running or walking.

**Comment by kispintyi** [comment]
The crossbow issue we previously talked about is real, you can see it even better in this clip:

Just look at 0:18 I loaded it but then when I wanted to shoot it just started charging.
It's a desync with the server and the client.
I suggest that maybe Noxesium can fix this by communicating it with the server or something because it's annoying.


​Active mods

Lunar Client

mods enabled in LC:

3D Skins, Armor Status, Block Outline, Boss Bar, Chat, Clock, Cooldowns, Crosshair, Damage Tint, Fov Changer, FPS, Hit Color, Hurt Cam, Item Counter, Menu Blur, Mumble Link, NameTags, Pack Organizer, Ping, Playtime, Potion Effects, Replay Mod, Saturation, Scoreboard, Screenshot Uploader, Scrollable Tooltips, Shiny Pots, Shulker Preview, Team View, Titles, WorldEdit CUI, Zoom

https://github.com/Noxcrew/noxesium/assets/116653691/b60a9488-e2b1-419f-98cf-c87df925a60e

Alternate link: https://cdn.discordapp.com/attachments/1134515300742733985/1182692678803136603/Clip_-_2023_12_08_153035.mp4?ex=65859f63&is=65732a63&hm=959c473ca9032f25e637bb44a4034100e58db7e6809a9a4f93c09aae05d1eb91&

**Comment by Aeltumn** [comment]
After considering this for some time I think these changes are out of scope for a single issue, and also not currently a focus. I'd be interesting to look into patching some vanilla bugs in the future but fixing desyncs conceptually is a big ask. If I find any particular issues that can be investigated those can be separate goals.

**Comment by kispintyi** [comment]
> The crossbow issue we previously talked about is real, you can see it even better in this clip:
> 
> Just look at 0:18 I loaded it but then when I wanted to shoot it just started charging. It's a desync with the server and the client. I suggest that maybe Noxesium can fix this by communicating it with the server or something because it's annoying.
> 
> ​Active mods
> 
> Lunar Client
> 
> mods enabled in LC:
> 
> 3D Skins, Armor Status, Block Outline, Boss Bar, Chat, Clock, Cooldowns, Crosshair, Damage Tint, Fov Changer, FPS, Hit Color, Hurt Cam, Item Counter, Menu Blur, Mumble Link, NameTags, Pack Organizer, Ping, Playtime, Potion Effects, Replay Mod, Saturation, Scoreboard, Screenshot Uploader, Scrollable Tooltips, Shiny Pots, Shulker Preview, Team View, Titles, WorldEdit CUI, Zoom
> 
>  Clip_-_2023_12_08_153035.mp4 
> Alternate link: https://cdn.discordapp.com/attachments/1134515300742733985/1182692678803136603/Clip_-_2023_12_08_153035.mp4?ex=65859f63&is=65732a63&hm=959c473ca9032f25e637bb44a4034100e58db7e6809a9a4f93c09aae05d1eb91&

Maybe this has to do with it: https://bugs.mojang.com/browse/MC-149075
