### ISSUE TITLE
Experimental settings removes 3rd party UI elements

### ISSUE THREAD

**Issue by DillPickle66** [Noxcrew/noxesium#42]
![2023-12-16_17 15 15](https://github.com/Noxcrew/noxesium/assets/136403943/84efe5ff-2464-43b5-ac56-6d65ceee2ec3)
![2023-12-16_17 15 30](https://github.com/Noxcrew/noxesium/assets/136403943/84df1ad8-ebba-4386-b0f4-ac2d5fedaf22)
Here I used Feather Client's UI but I also enabled Sodium's FPS counter and coordinates to show it wasn't just Feather UI causing the issue. The first screenshot is with experimental settings, the second is without.

**Comment by Aeltumn** [comment]
This has been addressed in the 1.20.3/1.20.4 version of the mod, 3rd party UI elements are not supported and won't be supported directly by Noxesium, but I will look into making it so they do show up, just aren't optimized when the experimental changes get more stable.

The experimental settings also auto-disable themselves on Feather now as I just can't support it. The setting's description also indicates that it does not support 3rd party mods in the new version.
