### ISSUE TITLE
[incompatibility] Remove use of @Overwrite

### ISSUE THREAD

**Issue by showierdata9978** [Noxcrew/noxesium#43]
Causes incompatibility's with mods that need to change how block entity's are rendered when mixing into Sodium

(this specific incompatibility was from https://github.com/Noxcrew/noxesium/blob/main/fabric/src/main/java/com/noxcrew/noxesium/mixin/beacon/SodiumWorldRendererMixin.java#L35-L43)

**Comment by Aeltumn** [comment]
Will all be removed in the next release.
See https://github.com/Noxcrew/noxesium/commit/98a421bc3e02c5185a05f4afe5767fd014995442
