### ISSUE TITLE
[Crash] net.minecraft.class_1768 was loaded too early

### ISSUE THREAD

**Issue by xR4YM0ND** [Noxcrew/noxesium#45]
[latest.log](https://gist.github.com/xR4YM0ND/18215fd0b71e19944130008a26eb6c4a)

**Comment by Aeltumn** [comment]
This seems to be an issue that has been fixed on the 1.20.4 version of the mod already. Could you possibly confirm whether it occurs on the latest version?

**Comment by xR4YM0ND** [comment]
I sadly can't.. it works with only these 2 mods (+ fabric api)

But it seems like that another mod in this pack is causing that..
