### ISSUE TITLE
Potential Ghosting Issues with latest version (1.3)

### ISSUE THREAD

**Issue by suitsnap** [Noxcrew/noxesium#48]
In the latest version a feature that added the ability to render teams as glowing. This feature was limited to where it will only activate when the client player is a spectator, most likely from having died. However, I think this could lead to potential issues with parties ghosting with ease in public games.

Example:
- Two parties of 4 have queued into the same Battle Box game where one party has this feature and the other does not. Say 3 players from each team die, the surviving player on the team who has the glowing feature seems more likely to win because it reduces the chance for the other player to sneak up, if that makes sense. On especially closed off maps, such as Pipes, having spectators who can communicate with the living person with even more ease than usual could potentially be detrimental.

Suggestion:
If this were an issue worth fixing, I would suggest limiting the glowing only being shown when the player either joins the game as a spectator, e.g. the spectator pool of a Plobby, or when their entire team has died.

**Comment by Aeltumn** [comment]
This is not really fixable or even worth fixing. If you have teammates ghosting there is nothing I can do to change that. Whether they can use glowing or they use the compass to teleport directly they can ghost all they want. If teammates ghosting is a problem in tournaments we can always make dead team members not become spectators in that case. But that is something to care about the on the server/organisation side. The actual feature can just be on when you are a spectator.

**Comment by suitsnap** [comment]
I didn't mean in tournaments, I just meant in general gameplay, but I understand the reasoning.

**Comment by Aeltumn** [comment]
> I didn't mean in tournaments, I just meant in general gameplay, but I understand the reasoning.

Yeah, I just don't see it being fixable or that big of a deal in normal games. It only feels like something that warrants fixing in tournaments at best.
