### ISSUE TITLE
Render player heads instead of ambiguous icons

### ISSUE THREAD

**Issue by cadenkriese** [Noxcrew/noxesium#5]
This feature was removed server side; it would be nice if it could be re-implemented through Noxesium since I know it already had a more performant approach. I was hesitant to create this issue for fear it was a duplicate of #3, but now that heads are removed server side, I think it's different enough to warrant a separate issue.

**Comment by Aeltumn** [comment]
If you look through the code you'll see there's already a system to render skull components client-side, we've just not gotten around to implementing it on the server-side.

**Comment by cadenkriese** [comment]
Does Noxcrew wish for this mod not to add any new features and only to act as an enhancement? I'm asking because I wanted to know if it's in scope to ask this mod to implement these icons in the boss bar/scoreboard without the server.

**Comment by Aeltumn** [comment]
We'll implement things into this mod in the most efficient way possible, and for player heads that means having the server detect users using Noxesium and sending a custom text component that the client can detect and replace with a skull component. Writing something for the client to detect when a server is trying to send a player head is much more difficult than integrating it properly.

It's just not been a priority to implement player skulls as they are so laggy that we cannot reasonably use them outside of people running Noxesium, so we aren't going to design UIs around them as we don't expect most users to see that anyway.

**Comment by Aeltumn** [comment]
Implemented as of v0.1.4.
