### ISSUE TITLE
The game crashes at startup.

### ISSUE THREAD

**Issue by EmptyDreams** [Noxcrew/noxesium#50]
Crash log:

[crash-2024-03-09_10.57.19-client.txt](https://github.com/Noxcrew/noxesium/files/14544730/crash-2024-03-09_10.57.19-client.txt)

**Comment by Aeltumn** [comment]
This issue has been fixed on the 1.20.4 version of Noxesium. 1.20.1 is no longer supported.

**Comment by EmptyDreams** [comment]
> This issue has been fixed on the 1.20.4 version of Noxesium. 1.20.1 is no longer supported.

Migrating all modules from 1.20.1 to 1.20.4 may be a big project, could you please release a version of 1.20.1 along the way?

Please ignore my request if releasing the 1.20.1 module at the same time is troublesome.

**Comment by Aeltumn** [comment]
There's been a large amount of changes since Noxesium's last 1.20.1 version. I would just suggest not using Noxesium if you want to use porting_lib. Noxesium doesn't offer many benefits if you're not playing multiplayer servers, so you might not need it.

**Comment by EmptyDreams** [comment]
> There's been a large amount of changes since Noxesium's last 1.20.1 version, so I can't really maintain it. I would just suggest not using Noxesium if you want to use porting_lib. Noxesium doesn't offer many benefits if you're not playing multiplayer servers, so you might not need it.

Okey, thanks for your patient response.
