### ISSUE TITLE
[1.20.6] Chat does not get removed when performance patches are applied

### ISSUE THREAD

**Issue by derNiklaas** [Noxcrew/noxesium#64]
I just updated to 1.20.6 and noticed that the chat message don't disappear when running the performance patches, here are two screenshots with and without the performance patches

![image](https://github.com/Noxcrew/noxesium/assets/12937331/eefc097e-75d2-479e-be6d-cf33e0192df3)
![image](https://github.com/Noxcrew/noxesium/assets/12937331/559378fc-4080-4efd-9df9-b7b1bfac5bf9)

**Comment by Aeltumn** [comment]
Will be fixed in v2.0.5.
