### ISSUE TITLE
Incompatible with Create mod

### ISSUE THREAD

**Issue by Fyoncle** [Noxcrew/noxesium#68]
yeah, it is.

**Comment by Aeltumn** [comment]
Could you provide additional details on what features of Noxesium and/or Create are being broken? Is there a crash on start-up?

**Comment by Fyoncle** [comment]
Yeah, just crash.

**Comment by Aeltumn** [comment]
And which version of Noxesium & Create that you are using.

**Comment by Fyoncle** [comment]
> And which version of Noxesium & Create that you are using.

Noxesium Latest at 1.20.1 Fabric, and latest Create

**Comment by Aeltumn** [comment]
Noxesium for 1.20.1 has a number of known compatibility issues that have since been fixed. It would be more relevant to test if these compatibility issues still exist on 1.20.6.

**Comment by Aeltumn** [comment]
If you have the crash report I can confirm whether the issue should be fixed in the latest version or not.

**Comment by Fyoncle** [comment]
I don't have crash report at the moment, sorry.

**Comment by Aeltumn** [comment]
Then I'll close it for now, if you have a crash report on the latest versions of Noxesium and Create it's something I can investigate further. Otherwise it's likely just a past issue that's nosw fixed.

**Comment by Fyoncle** [comment]
> Member

What known incompatibilites also? which mods?
