### ISSUE TITLE
Incompatible with Create Mod

### ISSUE THREAD

**Issue by Fyoncle** [Noxcrew/noxesium#70]
Hey there! I am here for the second time to notify you for the incompatibility about Create Mod, but this time, with a log!

https://mclo.gs/prknNnJ

Enjoy fixing it!

**Comment by Aeltumn** [comment]
This incompatibility has been resolved on the latest version. I'm not interested in backporting the change to 1.20.1 at this time, but it's fixed on 1.20.5 and newer.

**Comment by Fyoncle** [comment]
Oh :(
