### ISSUE TITLE
fabric 1.21 when?

### ISSUE THREAD

**Issue by Legendmanj** [Noxcrew/noxesium#86]
update them mod (;

thank you, apprreciate it if you do so and its a great mod gg

**Comment by Aeltumn** [comment]
An early version of the mod is already available for 1.21 here on Github. Its release on Modrinth is waiting on some bug testing I want to do on some of the new features. It got delayed a bit because of holidays.

**Comment by Legendmanj** [comment]
> An early version of the mod is already available for 1.21 here on Github. Its release on Modrinth is waiting on some bug testing I want to do on some of the new features. It got delayed a bit because of holidays.

 the latest version of noxesium is for 2.0.5 on modrinth and github, would you mind sourcing me to the 1.21 in github as mentioned?

**Comment by Aeltumn** [comment]
https://github.com/Noxcrew/noxesium/releases/tag/v2.1.0-rc1
It shows up when you click on the Releases tab, GitHub only shows the latest stable build on the main page.
