### ISSUE TITLE
add optimization for glowing effect

### ISSUE THREAD

**Issue by justaguywhowantsminecraftmods** [Noxcrew/noxesium#92]
The glowing effect kills my fps. fps drop is more noticeable while actually in games

![image](https://github.com/user-attachments/assets/820332c8-b18d-4aa6-80b9-8c6728a5a23f)
![image](https://github.com/user-attachments/assets/ace8c375-9545-49ad-b3d2-9893a92b2da6)

**Comment by Aeltumn** [comment]
The glowing effect is unfortunately not something I can easily optimize. It's performance depends heavily on which GPU you use which is not something I've got enough knowledge about to look into.
