### ISSUE TITLE
Noxesium causes error kick when switching between some servers

### ISSUE THREAD

**Issue by trolliant** [Noxcrew/noxesium#98]
I've had issues specifically with Noxesium whilst playing on a server called play.bingomc.net, specifically when switching between servers (tested between the two lobby servers, although sometimes happens in game too) this error pops up. Not sure exactly what causes it as it only seems to happen some of the time, but happy to give any other needed information.
![image](https://github.com/user-attachments/assets/5e66615d-442b-46d3-be8f-121620bc02cf)

**Comment by Aeltumn** [comment]
This will be fixed in the next update. (#97)
